### PR TITLE
fix/431: remove usage of `FILTER_SANITIZE_STRING`

### LINKED ISSUE #431: Update all uses of `FILTER_SANITIZE_STRING`
### Describe the bug

There's a handful of places within the codebase (I believe all within the `ComputerVision` class) where we are using the `FILTER_SANITIZE_STRING` constant within a `filter_input` call.

This constant has been deprecated in PHP 8.1 so we should look to change this to something that is fully supported. PHP's [documentation](https://www.php.net/manual/en/filter.filters.sanitize.php) suggests using `htmlspecialchars` instead though seems like there's some disagreement on that

### Steps to Reproduce

Within an environment running PHP 8.1 and debug turned on, note that deprecation warnings will show.

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Sidsector9**
### Description of the Change

Adds a helper method to sanitise `$_GET` and `$_POST` variables.

Closes #431

### Changelog Entry

> Fixed - Remove use of deprecated `FILTER_SANITIZE_STRING` constant

### Credits

Props @Sidsector9 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: includes/Classifai/Helpers.php [hunk 1]
```diff
@@ -615,3 +615,29 @@ function get_asset_info( $slug, $attribute = null ) {
 
 	return $asset;
 }
+
+
+/**
+ * Sanitizes input variables.
```
Comment (dkotter) [inline includes/Classifai/Helpers.php]:
```suggestion
 * Sanitizes and ensures an input variable is set.
```

File: includes/Classifai/Helpers.php [hunk 2]
```diff
@@ -615,3 +615,29 @@ function get_asset_info( $slug, $attribute = null ) {
...
+ *
+ * @param string  $key               $_GET or $_POST array key.
+ * @param boolean $is_get            if the request is $_GET. Default to false.
```
Comment (dkotter) [inline includes/Classifai/Helpers.php]:
```suggestion
 * @param boolean $is_get            If the request is $_GET. Defaults to false.
```

File: includes/Classifai/Helpers.php [hunk 3]
```diff
@@ -615,3 +615,29 @@ function get_asset_info( $slug, $attribute = null ) {
...
+ * @param string  $sanitize_callback Santize callback. Defaults to `sanitize_text_field`
```
Comment (dkotter) [inline includes/Classifai/Helpers.php]:
```suggestion
 * @param string  $sanitize_callback Sanitize callback. Defaults to `sanitize_text_field`
```

File: includes/Classifai/Helpers.php [hunk 4]
```diff
@@ -615,3 +615,29 @@ function get_asset_info( $slug, $attribute = null ) {
...
+ *
+ * @return string|boolean Sanitized string or `false` as fallback.
+ */
+function clean_input( $key, $is_get = false, $sanitize_callback = 'sanitize_text_field' ) {
```
Comment (dkotter) [inline includes/Classifai/Helpers.php]:
```suggestion
function clean_input( string $key = '', boolean $is_get = false, string $sanitize_callback = 'sanitize_text_field' ) {
```

**Review by dkotter — DISMISSED** [review]

File: includes/Classifai/Helpers.php [hunk 5]
```diff
@@ -615,3 +615,29 @@ function get_asset_info( $slug, $attribute = null ) {
...
+/**
+ * Sanitizes and ensures an input variable is set.
+ *
+ * @param string  $key               $_GET or $_POST array key.
+ * @param boolean $is_get            If the request is $_GET. Defaults to false.
+ * @param string  $sanitize_callback Sanitize callback. Defaults to `sanitize_text_field`
+ *
+ * @return string|boolean Sanitized string or `false` as fallback.
+ */
+function clean_input( string $key = '', boolean $is_get = false, string $sanitize_callback = 'sanitize_text_field' ) {
```
Comment (dkotter) [inline includes/Classifai/Helpers.php]:
```suggestion
function clean_input( string $key = '', bool $is_get = false, string $sanitize_callback = 'sanitize_text_field' ) {
```
