### PR TITLE
Ensure we don't send unnecessary API requests to NLU

### LINKED ISSUE #415: Ensure we don't send unnecessary requests to the Watson API
### Describe the bug

While testing #405 I noticed I was getting HTTP requests to the Watson API even when on the OpenAI settings page. In investigating further, I was seeing requests to this API on every single page load, including the front-end. This can result in potentially thousands of extra API requests on sites with lots of traffic.

In investigating this, the issue is in the `can_register` method of the `NLU` class. The `can_register` method for each `Provider` is called on `init`, so this code runs on all requests. The problem in the `NLU` class is we make an authentication request within `can_register`, so we hit the API on every single request.

This may have just been an oversight when this was built or it may have been done purposely to ensure we always have a valid connection but I would classify this as a bug that we need to fix. I would suggest we change how this works to match what we do for [ComputerVision](https://github.com/10up/classifai/blob/develop/includes/Classifai/Providers/Azure/ComputerVision.php#L1019) and [ChatGPT](https://github.com/10up/classifai/blob/develop/includes/Classifai/Providers/OpenAI/ChatGPT.php#L225), where we check these credentials when settings are saved and store the result of that, which we then check in the `can_register` methods.

The only downside I can think of is there is a scenario where credentials are valid when they are saved but later an API key may be revoked. Checking credentials more often allows us to alert the user sooner, though I don't think we are actually outputting any error message at the moment if that happens. So I don't think there's any issue with making this change.

### Steps to Reproduce

Install a plugin like Query Monitor and inspect the HTTP requests that are made on any page load

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dkotter**
### Description of the Change

As detailed in #415, there's a request on each page load (admin or front-end) to the NLU API to check to see if authentication is valid. These requests are unnecessary, leading to potential performance issues but more importantly, extra API usage.

This PR fixes that by refactoring the `can_register` method that all Providers use. For all other Providers besides NLU, we've removed the `can_register` method and instead rely on the parent `can_register` method.

For NLU, the `can_register` method now calls the `is_configured` method, which calls the parent `is_configured` method (matching what other providers do) but also checks the existing `classifai_configured` option to retain backwards compatibility. These changes fix the extra API requests, remove duplicate code and helps make things a little more consistent between Providers. 

Closes #415 

### How to test the Change

Ensure all Providers still work if configured properly and don't work if not configured properly

### Changelog Entry

> Changed - Standardize on how we determine if a Provider is configured
> Fixed - Avoid extra API requests to the NLU endpoint

### Credits

Props @dkotter, @benlk 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: includes/Classifai/Providers/Watson/NLU.php [hunk 1]
```diff
@@ -122,11 +123,7 @@ public function reset_settings() {
 	 * @return bool
 	 */
 	public function can_register() {
```
Comment (iamdharmesh) [inline includes/Classifai/Providers/Watson/NLU.php]: An optional nitpick: Maybe we can remove this method? As it is similar to the parent class `Provider`.

**Review by iamdharmesh — DISMISSED** [review]
Thanks for working on this and saving lots of requests @dkotter. LGTM. 🚀 

Thanks
