### PR TITLE
fix/315: add support for relative URLs

### LINKED ISSUE #315: Add support for relative path images
**Describe the bug**
In a [roots/bedrock](https://github.com/roots/bedrock) setup (custom wordpress folder structure), when I try to generate image tags/alt, i get an error :
`Error: Image URL is badly formatted.`

I tried with an image named `test.jpg` but the result is the same.

**Steps to Reproduce**
1. Go to Media library
2. Click on an image
3. Click on Classifai Alt Tags : Generate

**Expected behavior**
The alt tag / caption should be generated

**Screenshots**
image

**Environment information**
 - Device: Vagrant VM
 - OS: Ubuntu 21.04
 - Browser and version: Chrome 96.0.4664.45 (64 bits)
 - WordPress version: 5.8.2

 - <details><summary>Site Health Info:</summary>

    ### wp-core ###
      
    version: 5.8.2
    site_language: en_US
    user_language: en_US
    timezone: +02:00
    permalink: /%postname%/
    https_status: false
    multisite: false
    user_registration: 0
    blog_public: 1
    default_comment_status: open
    environment_type: production
    user_count: 1
    dotorg_communication: true
    
    ### wp-paths-sizes ###
    
    wordpress_path: /srv/www/v3/current/web/wp
    wordpress_size: loading...
    uploads_path: /srv/www/v3/current/web/app/uploads
    uploads_size: loading...
    themes_path: /srv/www/v3/current/web/app/themes
    themes_size: loading...
    plugins_path: /srv/www/v3/current/web/app/plugins
    plugins_size: loading...
    database_size: loading...
    total_size: loading...
    
    ### wp-active-theme ###
    
    name: Émergences RH Theme (ds-custom)
    version: 1.0
    author: Digital Swing
    author_website: https://www.digital-swing.com
    parent_theme: none
    theme_features: sage, widgets-block-editor, soil, menus, editor-color-palette, editor-gradient-presets, editor-font-sizes, custom-units, custom-line-height, custom-spacing, disable-custom-colors, disable-custom-gradients, disable-custom-font-sizes, title-tag, post-thumbnails, align-wide, responsive-embeds, html5, customize-selective-refresh-widgets, widgets
    theme_path: /srv/www/v3/current/web/app/themes/ds-custom
    
    ### wp-themes-inactive (11) ###
    
    Twenty Eleven: version: 3.9, author: the WordPress team
    Twenty Fifteen: version: 3.0, author: the WordPress team
    Twenty Fourteen: version: 3.2, author: the WordPress team
    Twenty Nineteen: version: 2.1, author: the WordPress team
    Twenty Seventeen: version: 2.8, author: the WordPress team
    Twenty Sixteen: version: 2.5, author: the WordPress team
    Twenty Ten: version: 3.5, author: the WordPress team
    Twenty Thirteen: version: 3.4, author: the WordPress team
    Twenty Twelve: version: 3.5, author: the WordPress team
    Twenty Twenty: version: 1.8, author: the WordPress team
    Twenty Twenty-One: version: 1.4, author: the WordPress team
    
    ### wp-mu-plugins (5) ###
    
    Bedrock Autoloader: version: 1.0.3, author: Roots
    Disable Update Notifications: version: 1.0, author: Digital Swing
    Disallow Indexing: version: 1.0.0, author: Roots
    Password bcrypt: version: 1.0.3, author: Roots
    Register Theme Directory: version: 1.0.0, author: Roots
    
    ### wp-plugins-active (24) ###
    
    Admin Columns Pro: version: 5.6.2, author: AdminColumns.com
    Admin Columns Pro - Advanced Custom Fields (ACF): version: 2.7, author: AdminColumns.com
    Advanced Custom Fields: Extended: version: 0.8.8.2, author: ACF Extended
    Akismet Anti-Spam: version: 4.2.1, author: Automattic
    Category Order and Taxonomy Terms Order: version: 1.5.7.6, author: Nsp-Code
    ClassifAI: version: 1.7.0, author: 10up
    Contact Form 7: version: 5.4, author: Takayuki Miyoshi
    FakerPress: version: 0.5.1, author: Gustavo Bordoni
    HTML Editor Syntax Highlighter: version: 2.4.4, author: James Bradford
    Imsanity: version: 2.7.2, author: Exactly WWW
    iThemes Security: version: 8.0.2, author: iThemes
    Nested Pages: version: 3.1.16, author: Kyle Phillips
    Post Types Order: version: 1.9.5.6, author: Nsp Code
    Post Views Counter: version: 1.3.9, author: Digital Factory
    Query Monitor: version: 3.7.1, author: John Blackbourn
    Rank Math SEO: version: 1.0.76.1, author: Rank Math
    Reading Time WP: version: 2.0.10, author: Jason Yingling
    Safe SVG: version: 1.9.9, author: Daryll Doyle
    Soil: version: 4.0.4, author: Roots
    Stream: version: 3.8.2, author: XWP
    Theme Check: version: 20200922.1, author: Theme Review Team
    WebP Express: version: 0.21.1, author: Bjørn Rosell
    WPBruiser: version: 3.1.43, author: Mihai Chelaru
    WP Redis: version: 1.1.4, author: Pantheon, Josh Koenig, Matthew Boynes, Daniel Bachhuber, Alley Interactive
    
    ### wp-plugins-inactive (8) ###
    
    ACF Field For Contact Form 7: version: 1.6, author: KrishaWeb
    Advanced Custom Fields: Phone Number: version: 1.1.6, author: Brandon Nifong
    CAOS: version: 4.1.8, author: Daan from FFW.Press
    Easy Table of Contents: version: 2.0.17, author: Steven A. Zahm
    Flamingo: version: 2.2.2, author: Takayuki Miyoshi
    reSmush.it Image Optimizer: version: 0.4.1, author: reSmush.it
    SF Taxonomy Thumbnail: version: 1.3, author: Grégory Viguier
    User Role Editor: version: 4.60.2, author: Vladimir Garagulya
    
    ### wp-media ###
    
    image_editor: WP_Image_Editor_Imagick
    imagick_module_version: 1690
    imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
    imagick_version: 3.5.1
    file_uploads: File uploads is turned off
    post_max_size: 32M
    upload_max_filesize: 64M
    max_effective_size: 32 MB
    max_file_uploads: 20
    imagick_limits: 
	    imagick::RESOURCETYPE_AREA: 122 MB
	    imagick::RESOURCETYPE_DISK: 1073741824
	    imagick::RESOURCETYPE_FILE: 768
	    imagick::RESOURCETYPE_MAP: 512 MB
	    imagick::RESOURCETYPE_MEMORY: 256 MB
	    imagick::RESOURCETYPE_THREAD: 1
    imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
    gd_version: 2.3.0
    gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
    ghostscript_version: 9.50
    
    ### wp-server ###
    
    server_architecture: Linux 5.4.0-58-generic x86_64
    httpd_software: nginx/1.21.4
    php_version: 7.4.25 64bit
    php_sapi: fpm-fcgi
    max_input_variables: 1000
    time_limit: 60
    memory_limit: 256M
    max_input_time: 60
    upload_max_filesize: 64M
    php_post_max_size: 32M
    curl_version: 7.68.0 OpenSSL/1.1.1f
    suhosin: false
    imagick_availability: true
    pretty_permalinks: true
    
    ### wp-database ###
    
    extension: mysqli
    server_version: 10.5.13-MariaDB-1:10.5.13+maria~focal
    client_version: mysqlnd 7.4.25
    
    ### wp-constants ###
    
    WP_HOME: http://v3.test
    WP_SITEURL: http://v3.test/wp
    WP_CONTENT_DIR: /srv/www/v3/current/web/app
    WP_PLUGIN_DIR: /srv/www/v3/current/web/app/plugins
    WP_MEMORY_LIMIT: 40M
    WP_MAX_MEMORY_LIMIT: 256M
    WP_DEBUG: true
    WP_DEBUG_DISPLAY: true
    WP_DEBUG_LOG: false
    SCRIPT_DEBUG: true
    WP_CACHE: false
    CONCATENATE_SCRIPTS: undefined
    COMPRESS_SCRIPTS: undefined
    COMPRESS_CSS: undefined
    WP_LOCAL_DEV: undefined
    DB_CHARSET: utf8mb4
    DB_COLLATE: undefined
    
    ### wp-filesystem ###
    
    wordpress: writable
    wp-content: writable
    uploads: writable
    plugins: writable
    themes: writable
    mu-plugins: writable
    
    ### classifai ###
    
    0: 1.7.0
    1: yes
    2: lucas@digital-swing.com
    3: 
	    Configured: no
	    API URL: 
	    API username: 
	    Post types: 
	    Features: {"category":null, "keyword":null, "entity":null, "concept":null}
	    Latest response: N/A
    4: 
	    Authenticated: yes
	    API URL: https://site-digital-swing.cognitiveservices.azure.com/
	    Caption threshold: 75
	    Latest response - Image Scan: Image URL is badly formatted.
	    Latest response - Smart Cropping: N/A
	    Latest response - OCR: Image URL is badly formatted.
</details>

### PR DESCRIPTION
**Pull request by Sidsector9**
### Description of the Change

Fixes issue reported by MS Computer Vision when the image URL is relative.

Closes #315

### Verification Process

1. Once you've connected to MS Computer Vision, set the following constant in the `wp-config.php` file to simulate the situation of the issue reporter.

```php
define( 'WP_CONTENT_URL', '/wp-content' );
```

2. Upload an image and confirm that the file URL shown is relative.
3. Generate Alt-tags by clicking the Rescan button
4. Observe the image

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/10up/.github/blob/trunk/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

> Fixed - bad URL error for relative URLs

### Credits

Props @Sidsector9 
Special props to @iamdharmesh for helping me out with the setup 🤓

### CODE REVIEW

File: includes/Classifai/Providers/Azure/ComputerVision.php [hunk 1]
```diff
@@ -528,6 +528,14 @@ protected function scan_image( $image_url, array $routes = [] ) {
 		$settings = $this->get_settings();
 		$url      = $this->prep_api_url( $routes );
 
+		/*
+		 * MS Comuter Vision requires full image URL. So, if the file URL is relative,
+		 * then we transform it into a full URL.
```
Comment (dinhtungdu) [inline includes/Classifai/Providers/Azure/ComputerVision.php]:
```suggestion
		 * MS Computer Vision requires full image URL. So, if the file URL is relative,
		 * then we transform it into a full URL.
```

**Review by dinhtungdu — DISMISSED** [review]
Got a small typo issue but the PR looks good! Thanks for working on this! :shipit:

File: includes/Classifai/Providers/Azure/ComputerVision.php (hunk 1 above)
Comment (Sidsector9) [reply includes/Classifai/Providers/Azure/ComputerVision.php]: Resolved in [51bd868](https://github.com/10up/classifai/pull/350/commits/51bd8688a2fdeec4b6133a522a2bd48fca5b72a9)

**Review by dinhtungdu — APPROVED** [review]
