### PR TITLE
Ensure we don't throw a fatal error if composer isn't set up correctly

### LINKED ISSUE #743: Fatal error: Missing format specifier at end of string in `classifai.php:91`
### Describe the bug

See in PHP 8.0.30

The `sprintf` function call doesn't include a format specifier for the string to be replaced. Instead of `%s` it's `%`.

https://github.com/10up/classifai/blob/fd8991c78b9ac4761a4740bbb974ccc0157d1ca4/classifai.php#L91

Running PHP 8.0 (and possibly other versions) this causes a fatal error during activation of the plugin.

### Steps to Reproduce

1. Configure classifai on a PHP 8.0 server
2. Run `npm i; composer i; npm run build` in the command line
3. Attempt to activate the plugin
4. Activation will fail due to a fatal error

### Screenshots, screen recording, code snippet

```
[07-Mar-2024 00:10:18 UTC] PHP Fatal error:  Uncaught ValueError: Missing format specifier at end of string in /vagrant/content/plugins/classifai/classifai.php:91
Stack trace:
#0 /vagrant/content/plugins/classifai/classifai.php(91): sprintf('Fatal Error: Co...', '/vagrant/conten...')
#1 /vagrant/content/plugins/classifai/classifai.php(116): classifai_autoload()
#2 /vagrant/content/plugins/classifai/classifai.php(152): classifai_autorun()
#3 /vagrant/wp-build/wp-admin/includes/plugin.php(2389): include_once('/vagrant/conten...')
#4 /vagrant/wp-build/wp-admin/includes/plugin.php(675): plugin_sandbox_scrape('classifai/class...')
#5 /vagrant/wp-build/wp-admin/plugins.php(60): activate_plugin('classifai/class...', 'http://xu-class...', false)
#6 {main}
  thrown in /vagrant/content/plugins/classifai/classifai.php on line 91
```

### Environment information

- PHP 8.0.30
- WordPress trunk @ 4d6941a48b230e0a40409f5732ab3dac1facb052 in the [wordpress/wordpress](https://github.com/wordpress/wordpress) repo

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dkotter**
### Description of the Change

We have some code that outputs an error message if `composer` hasn't been set up correctly but this code has a bug in it that ends up causing a fatal error instead. This PR fixes that issue and also removes the translation of this error message as no real need to translate strings that end up in the error log.

### How to test the Change

1. On the `develop` branch, clone the repo but don't run `composer install`
2. Activate the plugin and notice a fatal error happens
3. Run `composer install` and notice the error goes away
4. Checkout this branch and remove the `vendor` directory
5. Notice the fatal error doesn't happen anymore but an admin error notice shows instead

### Changelog Entry

> Fixed - Fix a fatal error that occurs if `composer install` hasn't been run

### Credits

Props @dkotter

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: classifai.php [hunk 1]
```diff
@@ -88,7 +88,7 @@ function classifai_autoload() {
 		return true;
 	} else {
 		error_log( // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
-			sprintf( esc_html__( 'Fatal Error: Composer not setup in %', 'classifai' ), CLASSIFAI_PLUGIN_DIR )
+			sprintf( 'Fatal Error: Composer not setup in %s', CLASSIFAI_PLUGIN_DIR )
```
Comment (peterwilsoncc) [inline classifai.php]:
```suggestion
			sprintf( 'Warning: Composer not setup in %s', CLASSIFAI_PLUGIN_DIR )
```

Or maybe notice, the error isn't fatal as Classifai catches it.

**Review by peterwilsoncc — COMMENTED** [review]
LGTM, just a note about it being a warning rather than an error.

Internationalization has been removed, was that intentional or did you just wish to get rid of the escaping?

**Comment by dkotter** [comment]
> Internationalization has been removed, was that intentional or did you just wish to get rid of the escaping?

Yeah, mentioned this in the PR description (though realize that's easy to miss) but my view was this is a message meant to be in the error log so doesn't seem like there's any real need to translate that. It's easy enough to add back though if you feel like it should be there.

**Review by peterwilsoncc — APPROVED** [review]
