### PR TITLE
Correctly add terms to posts generated by Watson content classifiers

### LINKED ISSUE #340: Terms/Tags are not getting created correctly when we select common taxonomy between enabled features.
### Describe the bug

During working on e2e using cypress PR(https://github.com/10up/classifai/pull/334), I noticed that when we select common taxonomy between enabled features, then terms/tags are not getting created correctly. Created terms/tags are not the combinations of the terms of the selected features instead it gets overwritten and ended up creating terms/tags of the only one feature. Please check screenshots for more information.

Based on the initial investigation this is happening because `wp_set_object_terms` overwrites terms/tags linked by other features
 https://github.com/10up/classifai/blob/develop/includes/Classifai/Watson/Linker.php#L116.

### Steps to Reproduce

1. Go to `ClassifAI` > `Language Processing` and setup API credentials
2. Enable All features (category, keywords, etc...) and assign related Watson taxonomy to each feature.
3. Create a post and note the terms created in each taxonomy.
4. Go to Language Processing settings and update "Tag" as a taxonomy for each feature.
5. Update a post created in step 3, check created tags. Created tags should be a combination of all terms created in step 3, but only a few tags are getting created.

### Screenshots, screen recording, code snippet

| Separate taxonomy for each features | Common taxonomy between features |
| --- | --- |
|image|image|

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ravinderk**
### Description of the Change

I found that we overwrite terms when adding new terms to a post. Admin can set same or different WordPress taxonomy for Watson `Category`,  `Keyword `, `Entity` & `Concept`. When the admin sets the same category for two or more Watson content classifiers, the term does not add correctly to the post. I update the logic to handle this use case.

Closes #340 

### How to test the Change

-  Add the same taxonomy to all Watson content classifiers in `ClassifAI` >` Language Processing` and the new post. The post should have the correct terms.
-  Add the different or same taxonomy to all Watson content classifiers in `ClassifAI` >` Language Processing` and the new post. The post should have the correct terms.

### Changelog Entry

> Fixed - Correctly add terms to posts generated by Watson content classifiers

### Credits

Props @iamdharmesh , @ravinderk

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: includes/Classifai/Watson/Linker.php [hunk 1]
```diff
@@ -33,24 +33,36 @@ class Linker {
...
-
+	 *
 	 * @return void
 	 */
 	public function link( $post_id, $output, $options = [] ) {
+		$all_terms = [];
+
 		if ( ! empty( $output['categories'] ) ) {
-			$this->link_categories( $post_id, $output['categories'] );
+			$terms = $this->link_categories( $post_id, $output['categories'], true );
```
Comment (dkotter) [inline includes/Classifai/Watson/Linker.php]: Getting a PHPCS warning here because the equals signs aren't aligned. Similar issue on lines 48, 53 and 58

File: includes/Classifai/Watson/Linker.php [hunk 2]
```diff
@@ -33,24 +33,36 @@ class Linker {
...
+			$all_terms = array_merge_recursive( $all_terms, $terms );
 		}
 
 		if ( ! empty( $output['entities'] ) ) {
-			$this->link_entities( $post_id, $output['entities'] );
+			$terms = $this->link_entities( $post_id, $output['entities'], true );
+			$all_terms = array_merge_recursive( $all_terms, $terms );
+		}
+
+		if ( $all_terms ) {
```
Comment (dkotter) [inline includes/Classifai/Watson/Linker.php]: Wondering if we want this to be `! empty( $all_terms )`

File: includes/Classifai/Watson/Linker.php [hunk 3]
```diff
@@ -73,9 +85,9 @@ public function link( $post_id, $output, $options = [] ) {
 	 *
 	 * @param int   $post_id The id of the post to link
 	 * @param array $categories The list of categories to link
-	 * @return void
```
Comment (dkotter) [inline includes/Classifai/Watson/Linker.php:76]: Should we change this to `@return array` instead of removing it?

File: includes/Classifai/Watson/Linker.php [hunk 4]
```diff
@@ -91,30 +103,27 @@ public function link_categories( $post_id, $categories ) {
...
+							$parent          = $term->term_id;
+							$terms_to_link[] = $term->term_id;
 						}
 					}
 				}
 			}
 		}
 
-		if ( ! empty( $terms_to_link ) ) {
+		if ( ! $return_terms ) {
```
Comment (dkotter) [inline includes/Classifai/Watson/Linker.php]: Seems like it would be good to keep the `! empty( $terms_to_link )` check here so we aren't trying to set an empty array of terms. If that seems right, would want to make that change in the other methods in this file

File: includes/Classifai/Watson/Linker.php [hunk 5]
```diff
@@ -73,9 +85,9 @@ public function link( $post_id, $output, $options = [] ) {
 	 *
 	 * @param int   $post_id The id of the post to link
 	 * @param array $categories The list of categories to link
-	 * @return void
+	 * @param bool  $return_terms Whether to return the terms to link or not
```
Comment (dkotter) [inline includes/Classifai/Watson/Linker.php]: I would suggest we change the logic here a bit. I think it's useful to always return the terms, I'd suggest instead this variable should determine whether we actually set the terms or not. So always return term data but we only set the terms here if this is `true` (which would be default).

**Review by dkotter — CHANGES_REQUESTED** [review]

**Comment by ravinderk** [comment]
@dkotter Pull request is ready for code review.

File: includes/Classifai/Watson/Linker.php [hunk 6]
```diff
@@ -71,11 +85,13 @@ public function link( $post_id, $output, $options = [] ) {
...
-	 * @param int   $post_id The id of the post to link
+	 * @param int   $post_id The id of the post to link.
 	 * @param array $categories The list of categories to link
-	 * @return void
+	 * @param bool  $link_terms Whether link terms to post or return terms.
+	 *
+	 * @return array|\WP_Error List of the terms to link. WP_Error class object on error.
 	 */
-	public function link_categories( $post_id, $categories ) {
+	public function link_categories( int $post_id, array $categories, bool $link_terms = false ) {
```
Comment (dkotter) [inline includes/Classifai/Watson/Linker.php]: Sorry, not to be super nit picky but thinking that 1) because these are existing methods that would link terms by default and 2) the names of these methods are `link_*`, I think we should keep them linking terms by default. So `$link_terms = true` and if you don't want that functionality, you'd pass in `false` there

**Review by dkotter — CHANGES_REQUESTED** [review]

File: includes/Classifai/Watson/Linker.php (hunk 6 above)
Comment (ravinderk) [reply includes/Classifai/Watson/Linker.php]: Resolved: https://github.com/10up/classifai/pull/462/commits/5b34d69e9bcbed87f6fa8279c6a96238bd02eee9

**Review by dkotter — APPROVED** [review]
